name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Check Node version
        run: node -v

      - run: npm install

      - run: npm run build

      - run: npx cap sync ios

      - name: Build iOS
        run: |
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -destination 'generic/platform=iOS Simulator' \
            build